### ISSUE TITLE
Support for `async` methods

### ISSUE THREAD

**Issue by pimbrouwers** [pimbrouwers/Donald#2]
Proposed API:

```f#
let queryAsync sql param conn = ... -> Task<'a list>
let querySingleAsync sql param conn = ... -> Task<'a>
let scalarAsync sql param conn = ... -> Task<'a>
let execAsync sql param conn = ... -> Task<unit>
let tranQueryAsync  sql param tran = ... -> Task<'a list>
let tranQuerySingleAsync sql param tran = ... -> Task<'a>
let tranScalarAsync sql param tran = ... -> Task<'a>
let tranExecAsync sql param tran = ... -> Task<unit>
```

**Comment by giuliohome** [comment]
Thank you for your async support and also for your kind response on the other thread (including the cautious approach about the DR Close). I agree that choosing async has to be evaluated at a specific business app level, but having the option to choose from a library is likely good, so thanks!

**Comment by pimbrouwers** [comment]
@giuliohome Explicit `IDataReader` close has been added in version 1.0.1!
