### ISSUE TITLE
TransactionBuilder

### ISSUE THREAD

**Issue by FoggyFinder** [pimbrouwers/Donald#23]
For example, [`FsSql.Core`](https://github.com/irium/FsSql/blob/master/FsSql/Transactions.fs) library has this feature that is handy when there're many queries in a single transaction.

**Comment by pimbrouwers** [comment]
Hello again!

Transactional work is already supported through the command expression. See this [example](https://github.com/pimbrouwers/Donald#execute-a-statement-within-an-explicit-transaction):

```fsharp
// Safely begin transaction or throw CouldNotBeginTransactionError on failure
use tran = conn.TryBeginTransaction()

// Build and execute the IDbCommand
dbCommand conn {
    cmdText  "INSERT INTO author (full_name)"
    cmdParam [ "full_name", SqlType.String "John Doe" ]
    cmdTran  tran
}
|> Db.exec // DbResult<unit>

// Attempt to commit, rollback on failure and throw CouldNotCommitTransactionError
tran.TryCommit()

// OR, safely rollback
tran.TryRollback()
```

**Comment by FoggyFinder** [comment]
> Transactional work is already supported through the command expression. See this example:

I'm aware but sample doesn't cover case with uh, let's say 2, 3 and more queries

For now my code looks like (parameters are omitted, names are different)

```fsharp
let addSomething obj1 obj2 = 
    use conn = openConn()
    use tran = conn.TryBeginTransaction()
    
    let res = 
        dbCommand conn {
            cmdText SQLQueries.someQuery1
            cmdParam [ ... ]
            cmdTran tran
        }
        |> Db.execSingle
    match res with
    | Result.Ok number ->
        let r2 = 
            dbCommand conn {
                cmdText SQLQueries.someQuery2
                cmdParam [ ... ]
                cmdTran tran
            }
            |> Db.execSingle
        match r2 with
        | Result.Ok id ->
            let r3 =
                dbCommand conn {
                    cmdText SQLQueries.someQuery3
                    cmdParam [ ... ]
                    cmdTran tran
                }
                |> Db.execSingle
                |> function | Result.Ok _ -> true | _ -> false

            if r3 then
                if tran.TryCommit () then
                   { obj1 with Id = id ; Number = number } |> Some
                else
                   None
            else
                tran.TryRollback () |> ignore
                None
        | Result.Error error ->
            tran.TryRollback () |> ignore
            None
    | Result.Error error ->
        tran.TryRollback () |> ignore
        None
```

maybe I use it in a wrong way?

**Comment by pimbrouwers** [comment]
Ahh, I see your issue now. You have multiple dependent commands executing within a transaction.

Without seeing your SQL I cannot tell whether this applies or not. But I personally will attempt to write most (if not all) work like this as a single SQL statement that will either all succeed (or fail) as a unit (in SQL Server `XACT_ABORT` ensure this for example). Since, as your code insinuates, this is often how these scenarios work anyway. It's much simpler to test and maintain in my experience.

That said, I fully acknowledge this is not always possible and I believe this example perfectly demonstrates the need for 
`DbResult.bind`, `DbResult.map` functions and an associated computation expression `dbResult { ... }`.

With that in place your code could become (keep in mind I wrote this in notepad):

```fsharp
let addSomething obj1 obj2 = 
    use conn = openConn()
    use tran = conn.TryBeginTransaction()

    dbResult {
        let! res = dbCommand conn {
            cmdText SQLQueries.someQuery1
            cmdParam [ ... ]
            cmdTran tran
        }
        |> Db.execSingle

        let! r2 = dbCommand conn {
            cmdText SQLQueries.someQuery2
            cmdParam [ ... ]
            cmdTran tran
        }
        |> Db.execSingle

        let! r3 = dbCommand conn {
            cmdText SQLQueries.someQuery3
            cmdParam [ ... ]
            cmdTran tran
        }
        |> Db.execSingle
        |> function | Result.Ok _ -> true | _ -> false

        if r3 then
            tran.TryCommit () |> ignore // this will rollback for you on failure
            Some { obj1 with Id = id ; Number = number }             
        else
            tran.TryRollback () |> ignore
            None
    }
```

**Comment by pimbrouwers** [comment]
Just added this in. You can test this out in the [6.1.0-beta1](https://www.nuget.org/packages/Donald/6.1.0-beta1) package if you'd like! Would love your feedback!

**Comment by FoggyFinder** [comment]
> Since, as your code insinuates, this is often how these scenarios work anyway. It's much simpler to test and maintain in my experience.

100%. I just don't know how to do it properly with SQLite. I'll add this to a task list of this project though. But since it is mainly for my use only I doubt I get to it soon.

> Just added this in. You can test this out in the 6.1.0-beta1 package if you'd like! Would love your feedback!

Wow! If I knew that it would be so fast I didn't spend so much time to write such awful code like the one above :-)

Just one thing: currently `For` method isn't supported, i.e.

```fsharp
let commands =
    xs
    |> Seq.map(fun item ->
        dbCommand conn {
            cmdText SQLQueries.someQuery
            cmdParam [ ... ]
            cmdTran tran
        }
    )

for command in commands do
    command
    |> Db.exec
```

Otherwise works smoothly. At least at first glance.

**Comment by pimbrouwers** [comment]
I'm so happy to hear that it worked out for you. It's been nice working together!

Your wish is my command: https://github.com/pimbrouwers/Donald/blob/d4576273fb0c2a2fb540a8ba8eefaf0cee64f12c/src/Donald.Tests/Tests.fs#L412

If you enjoy the lib, I'd love a star. And tell all your friends as they say :)

**Comment by FoggyFinder** [comment]
uh, and `Combine` method is required

A test that doesn't compile currently:

```fsharp
    [<Fact>]
    member __.``dbResult {...} for...do loop with return`` () =
        let cmds = 
            [1..10]
            |> Seq.map (fun n -> dbCommand conn {
                cmdText (sprintf "SELECT %i" n)
            })

        dbResult {
            for cmd in cmds do
                cmd |> Db.scalar Convert.ToInt32 |> ignore

            return 
                cmd |> Seq.head |> Db.scalar Convert.ToInt32
        }
        |> shouldNotBeError ignore
```

>If you enjoy the lib, I'd love a star.

I was a sixth one if github keeps the order in the stargazers list

**Comment by pimbrouwers** [comment]
Doh! I'll get that added in. 

(And thank you for you very early support)

**Comment by FoggyFinder** [comment]
Works like a charm

**Comment by subhashgorasiya** [comment]
Hey, @pimbrouwers, Thanks for this lightweight ADO.Net wrapper library.

Do you have any plan to support the transaction in Fluent syntax? 
I mostly prefer Fluent syntax and currently there is no any method to pass transaction to the Db.newCommand method.
