### ISSUE TITLE
[Help] How to parse results with sequential access?

### ISSUE THREAD

**Issue by ebrakke** [pimbrouwers/Donald#29]
Hello!
I'm pretty new to the F# world, and started to write an application using Falco with Donald.  I was following the setup of FalcoJournal for my application, however when I came to DB access, I kept getting a sequential access error.

```fsharp
module StateProvider = 
    type GetAll = unit -> DbResult<State list>
    let getAll (log : ILogger) (conn : IDbConnection) : GetAll =
        fun () ->
            let sql = "SELECT state, state_abbreviation FROM states;"

            let fromDataReader (rd : IDataReader) = 
                {StateAbbreviation = rd.ReadString "state_abbreviation"; State = rd.ReadString "state"}

            dbCommand conn { cmdText sql }
            |> Db.query fromDataReader
            |> DbResult.logError log
```
When I downgraded to version 5, I was able to get the code to work (change `Db.query` to `DbConn.query`)

I noticed that 5.0.* did not have sequential access turned on, which is why I assume it's working when I downgrade.  What would I need to update in this code for it to work with sequantial access turned on?

Thank you in advance, your work is much appreciated!

**Comment by pimbrouwers** [comment]
Hi Erik!

Thanks for checking out the library, and welcome to the F# community!

I apologize for the error but luckily it's an easy one to get around. The library is premised on sequential access which is what you already discovered. The benefit of this approach is that when interacting with an `IDataReader` the contents are streamed through. The drawback however is that the fields **must** be read in order. I'll be sure to go back and correct the FalcoJournal project and post as well.

The updated SQL statement should look like this:

```fsharp
let sql = "SELECT state_abbreviation, state FROM states;"
```

**Comment by pimbrouwers** [comment]
Hey Erik! Had a chance to try that out yet?
