### ISSUE TITLE
v.7.0.0

### ISSUE THREAD

**Issue by pimbrouwers** [pimbrouwers/Donald#35]
After some extended time using the library, it's become apparent to me that the type alias atop `Result<'a, DbExecutionError>` is providing little to no value. Aside from the source code type annotations being slightly less verbose. 

As such, I'm proposing that they be removed. I intend to preserve the `dbResult {}` and `dbResultTask {}` expressions, though I could easily be convinced to drop them now that we're relying on a more generic type.

```fsharp
open Donald

/* 
 * SqlType qualified access */
 
// New form
let sqlTypeInt = SqlType.Int 1

// Compiler error
let sqlTypeInt = Int 1 

/* 
 * DbResult & DbResultTask */

// New form
let readAuthor : Result<Author, DbExecutionError> = // ..
let readAuthor : Task<Result<Author, DbExecutionError>> = // ..

// Compiler error
let readAuthor : DbResult<Author> = // ...
let readAuthor : DbResultTask<Author> = // ...

// Still works (for now)
dbResult {}
dbResultTask {}
```

**Comment by pblasucci** [comment]
These seem very reasonable to me. 👍

**Comment by bddckr** [comment]
I've just did a similar change to a codebase at work myself! Turns out using type aliases like this, while saving a few characters to type, can easily confuse the dev working with it.

Without the aliases it's way easier to identify that the result Donald provides is a regular `Result`. Thus the user knows to not look for a `DbResult` module with the expected functions and instead can just use the `Result` module's functions.

Thumbs up from me as well!

**Comment by pimbrouwers** [comment]
@bddckr @pblasucci 

Any specific thoughts on the computation expressions? Including even the `dbCommand { }` which I regret in hindsight.

**Comment by bddckr** [comment]
IMO for `dbResult` and `dbResultTask` we can use any such builder other packages specifically offer. After all, this now is just a regular result and a regular task (with a specific value type).

`dbCommand` I've never personally used as I always found the pipe-able API way easier to use (and read in PR reviews).

**Comment by FoggyFinder** [comment]
Yes, it would be great to get rid of `DbResult` & `DbResultTask` types. Currently I have to map those into `Result`/`Option` every time. It's not very convenient indeed.

Btw, fluent syntax saved a lot of my time when I decided replace `Fumble` with `Donald` in one of my projects. Big thank you for such wonderful library that is getting better with each release.

**Comment by pimbrouwers** [comment]
Thanks so much Paul. I agree that the aliases and associated expressions are not great. Dropping them makes the library better for sure, at least in the sense of integrating into people's programs.

The dbCommand expression, I think you're right. It's nice syntax sugar and more importantly the original external form. I think preserving it will help ease the migration for some.
