### ISSUE TITLE
Support or Transition to Microsoft.Data.SqlClient

### ISSUE THREAD

**Issue by daniellittledev** [pimbrouwers/Donald#47]
The article [Introducing the new Microsoft.Data.SqlClient](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/) describes `Microsoft.Data.SqlClient` as the way forward for `ADO.NET`.

I propose this library either support or transition to `Microsoft.Data.SqlClient`

**Comment by pimbrouwers** [comment]
This package is agnostic. You can already use the newer NuGet package.

**Comment by daniellittledev** [comment]
🤯 wow, I didn't realise that was possible

**Comment by pimbrouwers** [comment]
Pretty neat huh! So it obviously is a double edged sword in some ways. But
the base abstractions expose enough functionality to be useful in most
circumstances.
