### ISSUE TITLE
SQLite: What SQL Type should I choose for a JSON column?

### ISSUE THREAD

**Issue by bytesource** [pimbrouwers/Donald#48]
Hi Pim, 

I'm wondering what SQL type I should use for a SQLite JSON column. Do I just need `SqlType.String` like this (`raw` is the JSON field):

``` fsharp
module Command = 

    let insertRawOrder orderId jsonString = {
        Sql = "INSERT INTO purchase (id, raw) VALUES (@id, @raw);"
        Params = [ 
            ("id",  SqlType.String orderId) 
            ("raw", SqlType.String jsonString) // SQLite JSON field
        ] 
    }
```

**Comment by pimbrouwers** [comment]
Great question! I think you've use the right internal type to jet that in there. Fundamentally, SQLite comes down to four internal types anyway. So my guess is that JSON is stored as string/CLOB data.

**Comment by bytesource** [comment]
You are right, JSON is represented as text. I just found this official statement:

> 3. Interface Overview
> SQLite stores JSON as ordinary text. Backwards compatibility constraints mean that SQLite is only able to store values that are NULL, integers, floating-point numbers, text, and BLOBs. It is not possible to add a sixth "JSON" type.

https://www.sqlite.org/json1.html
