### ISSUE TITLE
Incomplete newCommand on 'Execute a statement' examples

### ISSUE THREAD

**Issue by lc9er** [pimbrouwers/Donald#56]
Hello - just testing out the library and ran into errors running the 'Execute a statement' and 'Execute a statement many times' examples. The line reads:

`|> Db.newCommand "INSERT INTO author (full_name)"`

I could only get it to work if I changed it to

`|> Db.newCommand "INSERT INTO author (full_name) VALUES (@full_name)"`

Prior to the change, running the example would yield an error:

`Stopped due to error
\- conn
\- |> Db.newCommand "INSERT INTO author (full_name)"
\- |> Db.setParams [ "full_name", SqlType.String "Jane Fowl" ]
\- |> Db.exec;;
Donald.DbExecutionException: Failed to process database command:
@full_name = Jane Fowl

INSERT INTO author (full_name)
 ---> code = Error (1), message = System.Data.SQLite.SQLiteException (0x87AF001F): SQL logic error
incomplete input`

**Comment by pimbrouwers** [comment]
Thanks, I'll update the readme!
