### ISSUE TITLE
Add queryOne that requires one row?

### ISSUE THREAD

**Issue by njlr** [pimbrouwers/Donald#57]
Should we add `queryOne` that requires one row?

This could be used for queries like this:

```sql
SELECT COUNT(*) AS n FROM products
```

Signature like this:

```fsharp
    /// Execute paramterized query, read one record and apply mapping.
    let queryOne (map : 'reader -> 'a when 'reader :> IDataReader) (dbUnit : DbUnit) : 'a =
```

**Comment by pimbrouwers** [comment]
Apologies for the delay. Thanks for reaching out. 

This function exists already, checkout `Db.querySingle[Async]`.
