### ISSUE TITLE
How can I deal with database errors when executing statements?

### ISSUE THREAD

**Issue by Pekito** [pimbrouwers/Donald#58]
While I was reading the readme I checked that Db.exec alwas return an unit, but how could I know if the execution was successful or no? Is there any option that returns a Result monad?

**Comment by pimbrouwers** [comment]
Hi! Thanks for reaching out.

In version 10 there was an explicit migration away from `Result`, favoring CLR exceptions. The discussion can be found here: https://github.com/pimbrouwers/Donald/pull/54

As far as the library is concerned, if there are no exceptions thrown by the db vendor, things are ok. If you want this sort of monadic feedback. I'd recommend you convert `Db.exec` to `Db.scalar` or `Db.querySingle` and have the statement perform a query to verify success vs. failure.

Donald use to wrap up these exceptions (i.e., failed connection, execution or data read) into `Result`. But ultimately when any of those things happen there is really nothing to do but report/log there error.

You can easily create yourself a helper function to gobble up the 4 exception types emitted and wrap them in a `Result`. Perhaps this would be a useful add to the library... Something like: 

```fsharp
type DbConnectionError =
    { Message : string
      ConnectionString : string }

type DbExecutionError =
    { Message : string
      Statement : string }

type DbTransactionError =
    { Message : string
      Step : DbTransactionStep }

type DbReaderError =
    { Message : string
      FieldName : string }

type DbError =
    | DbConnectionError of DbConnectionError
    | DbTransactionError of DbTransactionError
    | DbExecutionError of DbExecutionError
    | DbReaderError of DbReaderError

module Db =
    let asResult (fn : DbUnit -> 'a) (dbUnit : DbUnit) =
        try
            Ok (fn dbUnit)
        with
        | :? DbConnectionException as ex ->
            DbConnectionError {
                Message = ex.Message
                ConnectionString = defaultArg ex.ConnectionString String.Empty }
            |> Error

        | :? DbTransactionException as ex ->
            DbTransactionError {
                Message = ex.Message
                Step = defaultArg ex.Step TxBegin }
            |> Error

        | :? DbExecutionException as ex ->
            DbExecutionError {
                Message = ex.Message
                Statement = defaultArg ex.Statement String.Empty }
            |> Error

        | :? DbReaderException as ex ->
            DbReaderError {
                Message = ex.Message
                FieldName = defaultArg ex.FieldName String.Empty }
            |> Error
```

This would allow you to do the following:

```fsharp
use conn = // db connection ...
conn
|> Db.newCommand ""
|> Db.asResult Db.exe
|> function
    | Ok x -> // .. 
    | Error e -> // ..
```

**Comment by Pekito** [comment]
> Hi! Thanks for reaching out.

Thank you too!! I'm really liking the developer experience of using Donald so far!


> In version 10 there was an explicit migration away from Result, favoring CLR exceptions. The discussion can be found here: https://github.com/pimbrouwers/Donald/pull/54

I see. In fact it can gets cumbersome handling multiple queries using the monadic return and you almost not gonna do anything useful with the `Error` value.

When I asked about this I was thinking of returning a specific error message to my web API if a query failed, naturally I thought about a Result monad but there is no problem using a Try catch as they're not really common, afterall.

> You can easily create yourself a helper function to gobble up the 4 exception types emitted and wrap them in a Result.

Thanks for the snippet!!

> Perhaps this would be a useful add to the library...

Are you intending to do this? I would love to get my hands dirty creating this `Db.tryExec` and `Db.tryQuery` methods.

**Comment by pimbrouwers** [comment]
> Thanks for the snippet!! 

My pleasure. Hope it helps!

> Are you intending to do this?

After some thought and sleep, I've decided not to include the monad-centered flow into the library. Overall, I find it's too opinionated and goes against the ethos of Result, I believe anyway. The library originally worked this way, and after many iterations I grew to realize it was all for naught, since there is nothing recoverable from these errors, they ultimately require developer intervention (i.e., they are _exceptional_).

**Comment by Pekito** [comment]
No problem!

I'm going to close this Issue
