### ISSUE TITLE
Add support for CommandType.StoredProcedure

### ISSUE THREAD

**Issue by willnationsdev** [pimbrouwers/Donald#7]
At my work, I've developed a similar lightweight framework where we pretty much only ever use stored procedures in our code. I'm wanting to make the move to an open source framework, and yours is the most promising, but we would prefer to be able to set the command type accordingly.

I envision that this could be done by creating some basic private functions that accept it as an argument and then reuse existing functions / add a new one to handle the versions that supply the extra parameter. Ex:

```fsharp
/// Create a new IDbCommand  
let newIDbCommand (sql : string) (tran : IDbTransaction) (cmdType : CommandType) =
    let cmd = tran.Connection.CreateCommand()
    cmd.CommandType <- cmdType
    cmd.CommandText <- sql
    cmd.Transaction <- tran
    cmd 

...

/// Create a new IDbCommand  
let newCommand (sql : string) (dbParams : DbParam list) (tran : IDbTransaction) (cmdType : CommandType) =
    let cmd = newIDbCommand sql tran cmdType 
    assignDbParams cmd dbParams
    cmd

...

let private tranOp (sql : string) (param : DbParam list) (map : IDataReader -> 'a) (tran : IDbTransaction) (cmdType : CommandType) =
    use cmd = newCommand sql param tran cmdType
    use rd = cmd.ExecuteReader()
    let results = [ while rd.Read() do yield map rd ]
    rd.Close() |> ignore
    results

/// Query for multiple results within transaction scope
let tranQuery (sql : string) (param : DbParam list) (map : IDataReader -> 'a) (tran : IDbTransaction) =
    tranOp sql param map tran CommandType.Text

///  for multiple results within transaction scope
let tranSproc (sql : string) (param : DbParam list) (map : IDataReader -> 'a) (tran : IDbTransaction) =
    tranOp sql param map tran CommandType.StoredProcedure

```

This then keeps the API consistent for things like `tranQuery` so as to not break compatibility too much.

I was gonna go ahead and work on that to submit a PR, but wanted to consult with you first to see if you even liked the implementation concept.

**Comment by pimbrouwers** [comment]
Howdy! 

Thanks for reaching out. I think this is a great idea, even though it may only server a small slice of people.

As opposed to adding sproc-variants to all the existing methods, which I'm worried would just further pollute the API, I've parameterized (as you suggested) the command type of `newIDbCommand`. Here's the relevant snippet from the source:

```f#
/// Create a new IDbCommand  
let newIDbCommand (commandType : CommandType) (sql : string) (tran : IDbTransaction) =
    let cmd = tran.Connection.CreateCommand()
    cmd.CommandType <- commandType
    cmd.CommandText <- sql
    cmd.Transaction <- tran
    cmd 

/// Create a new CommanType.Text IDbCommand  
let newTextDbCommand (sql : string) (tran : IDbTransaction) =
    newIDbCommand CommandType.Text sql tran

/// Create a new CommanType.StoredProcedure IDbCommand  
let newSprocDbCommand (sprocName : string) (tran : IDbTransaction) =
    newIDbCommand CommandType.StoredProcedure sprocName tran

/// Create a new CommandType.Text IDbCommand  
let newCommand (sql : string) (dbParams : DbParam list) (tran : IDbTransaction) =
    let cmd = newTextDbCommand sql tran
    assignDbParams cmd dbParams
    cmd

/// Create a new CommandType.Text IDbCommand  
let newSproc (sprocName : string) (dbParams : DbParam list) (tran : IDbTransaction) =
    let cmd = newSprocDbCommand sprocName tran
    assignDbParams cmd dbParams
    cmd
```

The presence of `newSproc` should allow for those needed the functionality to create Donald-style extensions for `Exec`, `Scalar`, `Query` etc. as needed.

Make sense?

v3.0.2, which includes this change, should be available on NuGet by the time you read this message :)

Ciao for now!

**Comment by willnationsdev** [comment]
This looks like a great change. The glories of open source! :-D I think this will enable us to proceed further. Thanks for your efforts.

**Comment by pimbrouwers** [comment]
@willnationsdev That honestly puts a big smile on my face. Thanks for touching base and using the library!

**Comment by willnationsdev** [comment]
Just commenting here to mention that, in practice, it became a real pain to have to manually create the query operations that used stored procedures instead of queries, but we still want to use stored procedures, so I recently just duplicated all of the functions with sproc versions. For anyone else that sees this Issue and wants a version of this repo that has full sproc support, they can get it [here](https://github.com/willnationsdev/Donald/tree/sproc). All functions just have a `Sproc` added to the end of their name, unless it ends in `Async`, in which case, it became `SprocAsync`. It's a ton of code duplication (sorry DRY), but the ease of use should be a lot better I think.
