### ISSUE TITLE
Doc comment error for newSproc

### ISSUE THREAD

**Issue by willnationsdev** [pimbrouwers/Donald#9]
FYI, it looks like the `newSproc` function you made never updated its doc comment to say `CommandType.StoredProcedure`. [Here](https://github.com/pimbrouwers/Donald/blob/master/src/Donald/Command.fs#L116).

**Comment by willnationsdev** [comment]
Also looks like the `d` in `CommandType` is missing in the doc comments for the other functions above, [here](https://github.com/pimbrouwers/Donald/blob/master/src/Donald/Command.fs#L102).

**Comment by pimbrouwers** [comment]
Solved by #12
